importScripts("precache-manifest.17f4a0cadf9f34270490e1d4c8c69207.js", "https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");

// manifest import and workbox imports will be autogenerated by webpack
workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
